// <auto-generated />
using System;
using Events.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Events.API.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20230405082305_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

      modelBuilder.Entity("Events.API.Models.Event", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<string>("Description")
                      .IsRequired()
                      .HasMaxLength(500)
                      .HasColumnType("TEXT");

            b.Property<DateTime>("EndDate")
                      .HasColumnType("TEXT");

            b.Property<Guid>("OwnerId")
                      .HasColumnType("TEXT");

            b.Property<DateTime>("StartDate")
                      .HasColumnType("TEXT");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Events");
          });

      modelBuilder.Entity("Events.API.Models.Invitation", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<Guid>("EventId")
                      .HasColumnType("TEXT");

            b.Property<string>("InviteState")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<Guid>("InviteeId")
                      .HasColumnType("TEXT");

            b.Property<Guid>("InviterId")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("EventId");

            b.ToTable("Invitations");
          });

      modelBuilder.Entity("Events.API.Models.User", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<string>("Email")
                      .HasMaxLength(50)
                      .HasColumnType("TEXT");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("TEXT");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("TEXT");

            b.Property<string>("UserName")
                      .IsRequired()
                      .HasMaxLength(20)
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Users");
          });

      modelBuilder.Entity("Events.API.Models.Invitation", b =>
          {
            b.HasOne("Events.API.Models.Event", null)
                      .WithMany("Invitations")
                      .HasForeignKey("EventId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });


#pragma warning restore 612, 618
    }
  }
}
